//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingAndConfigurationTest.WSMediaContent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", ConfigurationName="WSMediaContent.MediaContentService")]
    public interface MediaContentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="getMediaContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaDateModified[]))]
        PricingAndConfigurationTest.WSMediaContent.getMediaContentResponse1 getMediaContent(PricingAndConfigurationTest.WSMediaContent.getMediaContentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getMediaContent", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingAndConfigurationTest.WSMediaContent.getMediaContentResponse1> getMediaContentAsync(PricingAndConfigurationTest.WSMediaContent.getMediaContentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getMediaDateModified", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClassType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MediaDateModified[]))]
        PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedResponse1 getMediaDateModified(PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getMediaDateModified", ReplyAction="*")]
        System.Threading.Tasks.Task<PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedResponse1> getMediaDateModifiedAsync(PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaContentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private string cultureNameField;
        
        private mediaTypeType mediaTypeField;
        
        private string productIdField;
        
        private string partIdField;
        
        private int classTypeField;
        
        private bool classTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
                this.RaisePropertyChanged("wsVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=3)]
        public string cultureName {
            get {
                return this.cultureNameField;
            }
            set {
                this.cultureNameField = value;
                this.RaisePropertyChanged("cultureName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=4)]
        public mediaTypeType mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
                this.RaisePropertyChanged("mediaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=5)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=6)]
        public string partId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("partId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int classType {
            get {
                return this.classTypeField;
            }
            set {
                this.classTypeField = value;
                this.RaisePropertyChanged("classType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classTypeSpecified {
            get {
                return this.classTypeFieldSpecified;
            }
            set {
                this.classTypeFieldSpecified = value;
                this.RaisePropertyChanged("classTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/")]
    public enum mediaTypeType {
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Video,
        
        /// <remarks/>
        Audio,
        
        /// <remarks/>
        Document,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class ClassType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int classTypeIdField;
        
        private string classTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int classTypeId {
            get {
                return this.classTypeIdField;
            }
            set {
                this.classTypeIdField = value;
                this.RaisePropertyChanged("classTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string classTypeName {
            get {
                return this.classTypeNameField;
            }
            set {
                this.classTypeNameField = value;
                this.RaisePropertyChanged("classTypeName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class Decoration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int decorationIdField;
        
        private string decorationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int decorationId {
            get {
                return this.decorationIdField;
            }
            set {
                this.decorationIdField = value;
                this.RaisePropertyChanged("decorationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string decorationName {
            get {
                return this.decorationNameField;
            }
            set {
                this.decorationNameField = value;
                this.RaisePropertyChanged("decorationName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class Location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int locationIdField;
        
        private string locationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int locationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
                this.RaisePropertyChanged("locationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class MediaContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productIdField;
        
        private string partIdField;
        
        private string urlField;
        
        private mediaTypeType mediaTypeField;
        
        private ClassType[] classTypeArrayField;
        
        private double fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private decimal widthField;
        
        private bool widthFieldSpecified;
        
        private decimal heightField;
        
        private bool heightFieldSpecified;
        
        private int dpiField;
        
        private bool dpiFieldSpecified;
        
        private string colorField;
        
        private Decoration[] decorationArrayField;
        
        private Location[] locationArrayField;
        
        private string descriptionField;
        
        private bool singlePartField;
        
        private System.DateTime changeTimeStampField;
        
        private bool changeTimeStampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string partId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("partId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=3)]
        public mediaTypeType mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
                this.RaisePropertyChanged("mediaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClassType", IsNullable=false)]
        public ClassType[] ClassTypeArray {
            get {
                return this.classTypeArrayField;
            }
            set {
                this.classTypeArrayField = value;
                this.RaisePropertyChanged("ClassTypeArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("fileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
                this.RaisePropertyChanged("fileSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int dpi {
            get {
                return this.dpiField;
            }
            set {
                this.dpiField = value;
                this.RaisePropertyChanged("dpi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dpiSpecified {
            get {
                return this.dpiFieldSpecified;
            }
            set {
                this.dpiFieldSpecified = value;
                this.RaisePropertyChanged("dpiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=9)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Decoration", IsNullable=false)]
        public Decoration[] DecorationArray {
            get {
                return this.decorationArrayField;
            }
            set {
                this.decorationArrayField = value;
                this.RaisePropertyChanged("DecorationArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Location", IsNullable=false)]
        public Location[] LocationArray {
            get {
                return this.locationArrayField;
            }
            set {
                this.locationArrayField = value;
                this.RaisePropertyChanged("LocationArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=12)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool singlePart {
            get {
                return this.singlePartField;
            }
            set {
                this.singlePartField = value;
                this.RaisePropertyChanged("singlePart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=14)]
        public System.DateTime changeTimeStamp {
            get {
                return this.changeTimeStampField;
            }
            set {
                this.changeTimeStampField = value;
                this.RaisePropertyChanged("changeTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changeTimeStampSpecified {
            get {
                return this.changeTimeStampFieldSpecified;
            }
            set {
                this.changeTimeStampFieldSpecified = value;
                this.RaisePropertyChanged("changeTimeStampSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class MediaDateModified : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productIdField;
        
        private string partIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string partId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("partId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaContentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MediaContent[] mediaContentArrayField;
        
        private errorMessage errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MediaContent", IsNullable=false)]
        public MediaContent[] MediaContentArray {
            get {
                return this.mediaContentArrayField;
            }
            set {
                this.mediaContentArrayField = value;
                this.RaisePropertyChanged("MediaContentArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=1)]
        public errorMessage errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/")]
    public partial class errorMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaContentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public PricingAndConfigurationTest.WSMediaContent.GetMediaContentRequest GetMediaContentRequest;
        
        public getMediaContentRequest1() {
        }
        
        public getMediaContentRequest1(PricingAndConfigurationTest.WSMediaContent.GetMediaContentRequest GetMediaContentRequest) {
            this.GetMediaContentRequest = GetMediaContentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaContentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public PricingAndConfigurationTest.WSMediaContent.GetMediaContentResponse GetMediaContentResponse;
        
        public getMediaContentResponse1() {
        }
        
        public getMediaContentResponse1(PricingAndConfigurationTest.WSMediaContent.GetMediaContentResponse GetMediaContentResponse) {
            this.GetMediaContentResponse = GetMediaContentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaDateModifiedRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wsVersionField;
        
        private string idField;
        
        private string passwordField;
        
        private string cultureNameField;
        
        private System.DateTime changeTimeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=0)]
        public string wsVersion {
            get {
                return this.wsVersionField;
            }
            set {
                this.wsVersionField = value;
                this.RaisePropertyChanged("wsVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", DataType="token", Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=3)]
        public string cultureName {
            get {
                return this.cultureNameField;
            }
            set {
                this.cultureNameField = value;
                this.RaisePropertyChanged("cultureName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=4)]
        public System.DateTime changeTimeStamp {
            get {
                return this.changeTimeStampField;
            }
            set {
                this.changeTimeStampField = value;
                this.RaisePropertyChanged("changeTimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/")]
    public partial class GetMediaDateModifiedResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MediaDateModified[] mediaDateModifiedArrayField;
        
        private errorMessage errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MediaDateModified", IsNullable=false)]
        public MediaDateModified[] MediaDateModifiedArray {
            get {
                return this.mediaDateModifiedArrayField;
            }
            set {
                this.mediaDateModifiedArrayField = value;
                this.RaisePropertyChanged("MediaDateModifiedArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/SharedObjects/", Order=1)]
        public errorMessage errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaDateModifiedRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public PricingAndConfigurationTest.WSMediaContent.GetMediaDateModifiedRequest GetMediaDateModifiedRequest;
        
        public getMediaDateModifiedRequest1() {
        }
        
        public getMediaDateModifiedRequest1(PricingAndConfigurationTest.WSMediaContent.GetMediaDateModifiedRequest GetMediaDateModifiedRequest) {
            this.GetMediaDateModifiedRequest = GetMediaDateModifiedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaDateModifiedResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.promostandards.org/WSDL/MediaService/1.0.0/", Order=0)]
        public PricingAndConfigurationTest.WSMediaContent.GetMediaDateModifiedResponse GetMediaDateModifiedResponse;
        
        public getMediaDateModifiedResponse1() {
        }
        
        public getMediaDateModifiedResponse1(PricingAndConfigurationTest.WSMediaContent.GetMediaDateModifiedResponse GetMediaDateModifiedResponse) {
            this.GetMediaDateModifiedResponse = GetMediaDateModifiedResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MediaContentServiceChannel : PricingAndConfigurationTest.WSMediaContent.MediaContentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediaContentServiceClient : System.ServiceModel.ClientBase<PricingAndConfigurationTest.WSMediaContent.MediaContentService>, PricingAndConfigurationTest.WSMediaContent.MediaContentService {
        
        public MediaContentServiceClient() {
        }
        
        public MediaContentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediaContentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaContentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaContentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PricingAndConfigurationTest.WSMediaContent.getMediaContentResponse1 getMediaContent(PricingAndConfigurationTest.WSMediaContent.getMediaContentRequest1 request) {
            return base.Channel.getMediaContent(request);
        }
        
        public System.Threading.Tasks.Task<PricingAndConfigurationTest.WSMediaContent.getMediaContentResponse1> getMediaContentAsync(PricingAndConfigurationTest.WSMediaContent.getMediaContentRequest1 request) {
            return base.Channel.getMediaContentAsync(request);
        }
        
        public PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedResponse1 getMediaDateModified(PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedRequest1 request) {
            return base.Channel.getMediaDateModified(request);
        }
        
        public System.Threading.Tasks.Task<PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedResponse1> getMediaDateModifiedAsync(PricingAndConfigurationTest.WSMediaContent.getMediaDateModifiedRequest1 request) {
            return base.Channel.getMediaDateModifiedAsync(request);
        }
    }
}
